#!/bin/bash
#SBATCH --job-name=
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=16384
#SBATCH --cpus-per-task=1
#SBATCH --output=/home/cnmal2/scratch/art-inverse-dnn-fem/data/output_files/file-%j.ext1 
#SBATCH --error=/home/cnmal2/scratch/art-inverse-dnn-fem/data/output_files/file-%j.ext2 

/home/cnmal2/Mona0083/cnmal2/julias/julia-1.7.1/bin/julia /home/cnmal2/scratch/art-inverse-dnn-fem/src/ParameterSweep/MonARCH/Driver_DrWatson.jl
